server:
  port: 8080
  
spring:
  application:
    name: Customer
  zipkin:
    base-url: http://127.0.0.1:9411/
  rabbitmq:
    addresses: localhost:5672
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    hostname: localhost